version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8000"
    ports:
      - "8000:8000"

  web_service:
    image: solsson/http-echo@sha256:cadde771b6e022c3ea1a8ee84958d9b82ba5f7bda5f75730a8f8542d206c321c
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "80"
    ports:
      - "8080:80"

networks:
  envoymesh: {}
